#define STRING                  1 
#define DATE                    2 
#define BOOL                    3 
#define FLOAT                   4 
#define INTEGER                 5 
#define URL                     6 
#define CARGO                   7 
#define ESTADO                  8  
#define NULL_VALUE              9 
#define K_VERSION               10
#define K_FIRMA_DIGITAL         11
#define K_EMPRESAS              12
#define K_NOMBRE_EMPRESA        13
#define K_FUNDACION             14
#define K_DIRECCION             15
#define K_INGRESOS_ANUALES      16
#define K_PYME                  17
#define K_LINK                  18
#define K_CALLE                 19
#define K_CIUDAD                20
#define K_PAIS                  21
#define K_DEPARTAMENTOS         22
#define K_NOMBRE                23
#define K_JEFE                  24
#define K_SUBDEPARTAMENTOS      25
#define K_EMPLEADOS             26
#define K_EDAD                  27
#define K_CARGO                 28
#define K_SALARIO               29
#define K_ACTIVO                30
#define K_FECHA_CONTRATACION    31
#define K_PROYECTOS             32
#define K_ESTADO                33
#define K_FECHA_INICIO          34
#define K_FECHA_FIN             35