/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
static yyconst short int yy_acclist[100] =
    {   0,
       30,   30,   45,   43,   44,   30,   43,   44,   30,   44,
       43,   44,   41,   43,   44,   35,   43,   44,   42,   43,
       44,   39,   43,   44,   40,   43,   44,   43,   44,   43,
       44,   43,   44,   37,   43,   44,   38,   43,   44,   30,
       32,   35,   34,   34,   36,   33,    3,   32,   21,   32,
       18,   32,   12,   32,   15,   32,   11,   32,   13,   32,
       22,   32,    2,   32,   24,   32,   14,   32,   27,   32,
       17,   32,    1,   23,   32,    4,   32,    6,   32,   31,
       32,    9,   32,   20,   32,   29,    8,   32,   26,   32,
       28,   16,   32,    5,    7,   10,   19,   32,   25

    } ;

static yyconst short int yy_accept[389] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   13,   16,   19,
       22,   25,   28,   30,   32,   34,   37,   40,   41,   41,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   45,   45,   46,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   51,   51,   51,   51,   51,   51,
       51,   51,   53,   55,   55,   57,   57,   57,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   61,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   65,   65,
       65,   65,   65,   65,   67,   69,   69,   69,   69,   69,
       71,   71,   71,   71,   71,   71,   71,   73,   73,   73,
       73,   73,   73,   73,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   76,   76,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   82,   82,   82,   82,
       82,   82,   82,   84,   84,   86,   86,   87,   87,   87,
       89,   89,   89,   89,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   92,   92,   92,   92,   92,   92,   92,   94,   94,
       95,   95,   95,   95,   95,   95,   96,   96,   96,   96,
       96,   96,   96,   97,   99,   99,  100,  100
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   14,   14,   14,   14,   15,   16,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   20,   21,   21,
       21,   21,   22,   21,   21,   21,   23,   21,   24,   25,
       21,   21,   21,   26,   27,   21,   21,   28,   21,   21,
       29,    1,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   21,   48,   49,   50,   51,   52,   21,   21,
       53,   21,   54,    1,   55,    1,    1,    1,   56,    1,
        1,    1,    1,    1,    1,    1,   57,    1,    1,    1,
       58,    1,    1,    1,    1,    1,   59,    1,    1,    1,
        1,    1,    1,   60,    1,   61,    1,    1,    1,    1,
       62,    1,    1,    1,    1,    1,    1,    1,   63,    1,
        1,    1,   64,    1,    1,    1,    1,    1,   65,    1,
        1,    1,    1,    1,    1,   66,    1,   67,    1,    1,
        1,    1,    1,    1,   68,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    1,    1,    2,    2,    1,    2,    2,    1,    2,
        2,    2,    2,    2,    2,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2
    } ;

static yyconst short int yy_base[393] =
    {   0,
        0,   54,  707,  708,    5,   15,  106,  708,   12,  708,
      708,  708,  674,  654,  656,  708,  708,   29,   29,  708,
       33,   30,  164,  671,    3,  657,  669,  655,  651,  652,
      669,  662,    4,    6,   27,   37,  650,  658,  653,  646,
       42,   21,  655,  161,  150,  158,  647,  646,  637,  224,
      678,  641,  681,  632,  638,  678,  633,  676,  633,  674,
      673,  626,    4,  624,  627,  625,  640,  624,  620,  635,
      620,  622,  628,  628,  619,  619,   11,  616,  617,  617,
      626,  610,  230,  608,  613,  619,  241,  645,  619,  162,
       39,  616,  201,  609,  192,   45,  197,  117,  610,  606,

      610,  612,  614,  609,  609,   39,  611,  603,  597,  605,
      591,  602,  595,  603,  586,  570,  580,  596,  599,  595,
      580,  708,  592,  708,  708,  203,    0,  591,  198,  583,
      578,  619,  209,  587,  242,  571,  585,  244,  245,  568,
      583,  572,  585,  568,  581,  609,  577,  576,  576,  578,
      577,  576,  571,  601,  600,  556,  598,  210,  566,  596,
      552,  563,  558,  253,  589,  553,  256,  549,  545,  708,
      257,  543,   38,  558,  557,  110,  262,  544,  584,  583,
      552,  536,  551,  708,  552,  534,  536,  550,  549,  545,
      529,  708,  708,  541,  708,  207,  542,  708,  535,  527,

      527,  271,  284,    0,  536,  265,  524,  565,  263,  529,
      267,  518,  517,  268,  561,  708,  708,  560,  532,  523,
      527,  529,  555,  280,  524,  518,  511,   58,  506,  509,
      522,  508,  286,  310,  517,  282,  515,  708,  274,  505,
      545,  544,  269,  708,  708,  503,   32,  500,  496,  708,
      498,  503,  497,  501,  260,  491,  708,  503,  492,  532,
      488,  530,  333,  708,    0,  346,  294,  486,  327,  495,
      299,  318,  324,  496,  486,  465,  480,  523,  482,  481,
      485,  486,  478,  457,  490,  476,  470,  708,  468,  708,
      359,  370,  383,  329,   87,  393,  360,  344,  382,  363,

      472,  511,  371,  510,  708,  464,  501,  471,  464,  498,
      372,  470,  454,  494,  464,  708,  410,  361,  386,  385,
      395,  444,  708,  373,  708,  445,  708,  452,  441,  708,
      374,  443,  438,  708,  441,  447,  406,  432,  438,  451,
      427,  440,  418,  432,  431,  466,  429,  427,  399,  397,
      441,  393,  381,  347,  308,   98,  421,  430,  335,  266,
      708,  292,  237,  163,  144,  440,  439,  708,  159,  708,
      156,  177,  135,  137,   87,  708,   86,  387,  107,  100,
       57,   29,  708,  708,   88,  708,  708,  508,  510,   58,
       38,   25

    } ;

static yyconst short int yy_def[393] =
    {   0,
      388,  388,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  389,  387,
      389,  389,    7,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,  387,  387,  387,  387,  387,  387,  389,
      387,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,  387,  387,  387,  387,  389,  387,   23,  389,
       23,   23,  389,   23,  389,   23,  389,  389,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   44,   23,   23,   23,   23,
       23,  387,  387,  387,  387,  389,  390,   23,  389,   23,
       23,   23,  389,   23,  389,   23,   23,  389,  389,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,  389,   23,   23,
       23,   23,   23,  389,  390,   23,  389,   23,   23,  387,
      389,   23,  389,   23,   23,  389,  389,   23,   23,   23,
       23,   23,   23,  387,   23,   23,   23,   23,   23,   23,
       23,  387,  387,   23,  387,  389,   23,  387,   23,   23,

       23,  389,  389,  391,   23,  389,   23,   23,  389,   23,
      389,   23,   23,  389,   23,  387,  387,   23,   23,   23,
       23,   23,   23,  387,  387,   23,   23,   23,   23,   23,
       23,   23,  389,  391,   23,  389,   23,  387,  389,   23,
       23,   23,  389,  387,  387,   23,   23,   23,   23,  387,
      387,  387,  387,  387,   23,   23,  387,  387,   23,   23,
       23,   23,  389,  387,  392,  387,  389,   23,  389,   23,
      389,  389,  389,   23,   23,   44,   23,   23,  387,  387,
      387,  387,   23,   44,   23,  387,   23,  387,   23,  387,
      389,  389,  389,  389,  392,  387,  389,  389,  389,  389,

       23,   23,  389,   23,  387,  387,  387,  387,  387,   23,
      389,  387,  387,   23,   23,  387,  387,  389,  389,  389,
      389,   23,  387,  389,  387,  387,  387,  387,  387,  387,
      389,  387,  387,  387,   23,  387,  389,  389,   23,  387,
      387,  387,  387,  387,   23,  387,  389,  389,   23,  387,
      387,  387,  387,  387,   23,  387,  389,  389,   23,  387,
      387,  387,  387,  387,   23,  389,  389,  387,  387,  387,
      387,  387,   23,  387,  387,  387,   23,  387,  387,   23,
      387,  387,  387,  387,  387,  387,    0,  387,  387,  387,
      387,  387

    } ;

static yyconst short int yy_nxt[777] =
    {   0,
      387,    5,    6,    5,    7,    8,   18,   18,   18,    9,
        9,    9,    9,    9,    9,   10,   18,   18,   18,   45,
       53,   46,   46,   46,   46,   46,   46,  295,   11,   12,
       18,   18,   18,   20,   20,   63,   13,   20,   54,   50,
      234,   65,   20,   64,   14,   66,  100,   50,   55,   15,
      115,  101,   80,   16,   17,    5,    6,    5,    7,    8,
      165,   67,  257,    9,    9,    9,    9,    9,    9,   10,
       68,   81,   70,   77,  130,   69,   71,  275,  116,  136,
      211,  147,   11,   12,  131,  137,  148,   72,  258,   78,
       13,  264,  386,  381,   79,  265,   44,   44,   14,  276,

       44,  385,  264,   15,  384,   44,  265,   16,   17,   19,
       20,  383,   19,   19,  170,   19,   21,   22,   19,   19,
       19,   20,   23,   23,   24,   25,   23,   26,   27,   28,
       29,   30,   31,   23,  380,  379,  139,   32,   23,   33,
       34,   35,   36,   23,   23,   37,   38,   23,   39,   23,
       40,   23,   41,   23,   42,   23,   23,   43,   23,   83,
       83,   83,   83,   83,   83,   45,   20,   46,   46,   46,
       46,   46,   46,   44,   19,   19,  378,   44,  129,   51,
      377,  376,   23,   23,   44,   23,   23,   23,   23,   23,
       23,  375,  374,  373,  372,   23,   20,   23,   23,   23,

       23,   20,   20,   23,   23,   20,   23,   20,   23,  164,
       23,  195,   23,   20,   20,   23,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   20,   44,
      135,  138,  167,   87,   87,   87,   87,   87,   87,  122,
      122,  122,  122,  122,  122,   20,   20,  133,   20,   20,
      126,  126,  126,  126,  126,  126,  171,   20,  196,   44,
       20,   20,  202,  203,   44,   44,   20,   20,   44,   20,
       44,   20,   20,   20,   44,   20,   44,   44,   20,  371,
      177,  233,  233,  233,  233,  233,   20,  173,   20,  176,
       20,   44,  263,  233,  233,  233,  370,  369,  238,  206,

      239,  176,  209,   20,  236,  283,  273,  243,   44,   44,
      214,   44,   44,  251,  264,  298,  252,  204,  265,  253,
       44,  269,   20,   44,   44,  266,  267,  284,   20,   44,
       44,   20,   44,  316,   44,   44,   44,   20,   44,  368,
      299,   44,  291,  292,  292,  293,  294,  294,   20,   44,
      264,   44,  365,   44,  265,  296,  296,  296,  296,  296,
      296,   44,  297,   20,   20,   20,   44,   20,  300,  294,
      294,  294,  294,  294,  316,   20,   20,  323,  330,  294,
      294,  294,  294,  294,  294,   44,   20,  316,  319,   20,
       20,   44,  294,  294,   44,  364,   44,  264,  321,   20,

       44,  265,  317,  317,  317,  317,  317,  317,  318,  176,
       20,   44,  363,  320,  264,  324,  331,  337,  265,  336,
      336,  336,  336,  336,  336,   20,   44,   44,   44,  338,
       44,   20,  381,   20,   20,  362,   20,   44,   44,   44,
       44,   44,  267,   20,   20,  361,  360,  359,  347,   44,
       44,  264,   44,   44,  382,  265,  346,  346,  346,  346,
      346,  346,   44,  348,  358,  367,  355,  354,  353,  366,
      264,  352,  351,   44,  265,  356,  356,  356,  356,  356,
      356,  357,  350,  349,  345,  344,  267,  343,   44,  267,
      342,  341,  340,  339,   44,  335,   44,   44,  334,   44,

      333,  332,  330,  329,  328,  327,   44,   44,    4,    4,
        4,   19,   19,  326,  325,  323,  322,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  208,  208,  290,  289,  288,  287,  286,  285,
      282,  281,  280,  279,  278,  277,  274,  272,  271,  270,
      268,  132,  262,  261,  260,  259,  256,  255,  254,  250,
      249,  248,  247,  246,  245,  244,  242,  241,  240,  238,
      237,  235,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      213,  212,  210,  208,  207,  205,  204,  201,  200,  199,

      198,  197,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      175,  174,  172,  170,  169,  168,  166,  125,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  146,  145,  144,  143,  142,  141,  140,
      134,  132,  128,  127,  125,  124,  123,  121,  120,  119,
      118,  117,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,   99,   98,   97,   96,   95,
       94,   93,   92,   91,   90,   89,   88,   86,   85,   84,
       82,   76,   75,   74,   73,   62,   61,   60,   59,   58,

       57,   56,   52,   49,   48,   47,  387,    3,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387
    } ;

static yyconst short int yy_chk[777] =
    {   0,
        0,    1,    1,    1,    1,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    1,    6,    6,    6,    9,
       25,    9,    9,    9,    9,    9,    9,  392,    1,    1,
       18,   18,   18,   19,   22,   33,    1,   21,   25,   22,
      391,   34,  173,   33,    1,   34,   63,   21,   25,    1,
       77,   63,   42,    1,    1,    2,    2,    2,    2,    2,
      390,   35,  228,    2,    2,    2,    2,    2,    2,    2,
       35,   42,   36,   41,   91,   35,   36,  247,   77,   96,
      173,  106,    2,    2,   91,   96,  106,   36,  228,   41,
        2,  295,  385,  382,   41,  295,   19,   22,    2,  247,

       21,  381,  356,    2,  380,  173,  356,    2,    2,    7,
        7,  379,    7,    7,  176,    7,    7,    7,    7,    7,
        7,   98,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,  377,  375,   98,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,   45,
       45,   45,   45,   45,   45,   46,   90,   46,   46,   46,
       46,   46,   46,    7,   23,   23,  374,  176,   90,   23,
      373,  372,   23,   23,   98,   23,   23,   23,   23,   23,
       23,  371,  369,  365,  364,   23,   95,   23,   23,   23,

       23,   97,  129,   23,   23,   93,   23,  126,   23,  126,
       23,  196,   23,  133,  158,   23,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   50,   90,
       95,   97,  129,   50,   50,   50,   50,   50,   50,   83,
       83,   83,   83,   83,   83,   87,  135,   93,  138,  139,
       87,   87,   87,   87,   87,   87,  133,  164,  158,   95,
      167,  171,  164,  164,   97,  129,  177,  209,   93,  206,
      126,  211,  214,  243,  196,  202,  133,  158,  239,  363,
      139,  202,  202,  202,  202,  202,  236,  135,  203,  138,
      233,   50,  233,  203,  203,  203,  362,  360,  267,  167,

      209,  211,  171,  271,  206,  255,  243,  214,   87,  135,
      177,  138,  139,  224,  234,  271,  224,  234,  234,  224,
      164,  239,  272,  167,  171,  234,  236,  255,  273,  177,
      209,  269,  206,  294,  211,  214,  243,  263,  202,  359,
      272,  239,  263,  263,  263,  263,  263,  263,  298,  236,
      266,  203,  355,  233,  266,  266,  266,  266,  266,  266,
      266,  267,  269,  291,  297,  318,  271,  300,  273,  291,
      291,  291,  291,  291,  292,  303,  311,  324,  331,  292,
      292,  292,  292,  292,  292,  272,  299,  293,  298,  320,
      319,  273,  293,  293,  269,  354,  294,  296,  300,  321,

      263,  296,  296,  296,  296,  296,  296,  296,  297,  318,
      337,  298,  353,  299,  317,  303,  311,  319,  317,  317,
      317,  317,  317,  317,  317,  357,  291,  297,  318,  320,
      300,  348,  378,  347,  358,  352,  338,  292,  303,  311,
      324,  331,  321,  367,  366,  351,  350,  349,  337,  299,
      293,  336,  320,  319,  378,  336,  336,  336,  336,  336,
      336,  336,  321,  338,  348,  358,  345,  344,  343,  357,
      346,  342,  341,  337,  346,  346,  346,  346,  346,  346,
      346,  347,  340,  339,  335,  333,  367,  332,  357,  366,
      329,  328,  326,  322,  348,  315,  347,  358,  314,  338,

      313,  312,  310,  309,  308,  307,  367,  366,  388,  388,
      388,  389,  389,  306,  304,  302,  301,  289,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  270,  268,  262,  261,  260,  259,  258,  256,
      254,  253,  252,  251,  249,  248,  246,  242,  241,  240,
      237,  235,  232,  231,  230,  229,  227,  226,  225,  223,
      222,  221,  220,  219,  218,  215,  213,  212,  210,  208,
      207,  205,  201,  200,  199,  197,  194,  191,  190,  189,
      188,  187,  186,  185,  183,  182,  181,  180,  179,  178,
      175,  174,  172,  169,  168,  166,  165,  163,  162,  161,

      160,  159,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      137,  136,  134,  132,  131,  130,  128,  123,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  111,  110,
      109,  108,  107,  105,  104,  103,  102,  101,  100,   99,
       94,   92,   89,   88,   86,   85,   84,   82,   81,   80,
       79,   78,   76,   75,   74,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   62,   61,   60,   59,   58,
       57,   56,   55,   54,   53,   52,   51,   49,   48,   47,
       43,   40,   39,   38,   37,   32,   31,   30,   29,   28,

       27,   26,   24,   15,   14,   13,    3,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
#include <stdio.h>
#include <conio.h>
#include <string.h>
#include "../parser/parser.tab.c"
#ifndef STRING_BUFFER_SIZE
#define STRING_BUFFER_SIZE 1024
#endif

void showError( char *s);
void copyString();

#line 701 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 35 "lexer.l"



#line 856 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 388 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 708 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 38 "lexer.l"
{ printf("URL"); copyString(); return (URL); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "lexer.l"
{ printf("CARGO"); copyString(); return (CARGO); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "lexer.l"
{ printf("ESTADO"); copyString(); return (ESTADO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "lexer.l"
{ printf("K_VERSION"); return (K_VERSION); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "lexer.l"
{ printf("K_FIRMA_DIGITAL"); return (K_FIRMA_DIGITAL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "lexer.l"
{ printf("K_EMPRESAS"); return (K_EMPRESAS); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "lexer.l"
{ printf("K_NOMBRE_EMPRESA"); return (K_NOMBRE_EMPRESA); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "lexer.l"
{ printf("K_FUNDACION"); return (K_FUNDACION); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "lexer.l"
{ printf("K_DIRECCION"); return (K_DIRECCION); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "lexer.l"
{ printf("K_INGRESOS_ANUALES"); return (K_INGRESOS_ANUALES); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "lexer.l"
{ printf("K_PYME"); return (K_PYME); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "lexer.l"
{ printf("K_LINK"); return (K_LINK); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "lexer.l"
{ printf("K_CALLE"); return (K_CALLE); } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "lexer.l"
{ printf("K_CIUDAD"); return (K_CIUDAD); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "lexer.l"
{ printf("K_PAIS"); return (K_PAIS); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "lexer.l"
{ printf("K_DEPARTAMENTOS"); return (K_DEPARTAMENTOS); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "lexer.l"
{ printf("K_NOMBRE"); return (K_NOMBRE); } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("K_JEFE"); return (K_JEFE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("K_SUBDEPARTAMENTOS"); return (K_SUBDEPARTAMENTOS); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("K_EMPLEADOS"); return (K_EMPLEADOS); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("K_EDAD"); return (K_EDAD); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "lexer.l"
{ printf("K_CARGO"); return (K_CARGO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("K_SALARIO"); return (K_SALARIO); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("K_ACTIVO"); return (K_ACTIVO); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("K_FECHA_CONTRATACION"); return (K_FECHA_CONTRATACION); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("K_PROYECTOS"); return (K_PROYECTOS); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("K_ESTADO"); return (K_ESTADO); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("K_FECHA_INICIO"); return (K_FECHA_INICIO); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("K_FECHA_FIN"); return (K_FECHA_FIN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf(yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "lexer.l"
{ printf("DATE"); copyString(); return (DATE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("STRING"); copyString(); return (STRING); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "lexer.l"
{ printf("BOOL"); sscanf(yytext, "%s", yylval.boolean); return (BOOL); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "lexer.l"
{ printf("FLOAT"); yylval.number = atof(yytext); return (FLOAT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "lexer.l"
{ printf("INTEGER"); yylval.integer = atoi(yytext); return (INTEGER); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("NULL_VALUE"); return (NULL_VALUE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("BRACE_OPEN"); return (BRACE_OPEN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "lexer.l"
{ printf("BRACE_CLOSE"); return (BRACE_CLOSE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 76 "lexer.l"
{ printf("BRACKET_OPEN"); return (BRACKET_OPEN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 77 "lexer.l"
{ printf("BRACKET_CLOSE"); return (BRACKET_CLOSE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 78 "lexer.l"
{ printf("COMMA"); return (COMMA); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 79 "lexer.l"
{ printf("COLON"); return (COLON); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "lexer.l"
{ showError(yytext); return(OTRO); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1167 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 388 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 388 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 387);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 83 "lexer.l"


void copyString () {
    yylval.string = malloc( STRING_BUFFER_SIZE * sizeof(char) );
    strcpy( yylval.string, yytext );

    // Elimina comillas
    yylval.string++;
    yylval.string[strlen(yylval.string) - 1] = 0;
}

void printToken( char *token) {

    if ()
}


void showError ( char* s ) {
    fprintf(stderr, "[Error Lexico: Caracter invalido => \"%s\"]", s);
}

