#line 2 "lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
static yyconst short int yy_acclist[83] =
    {   0,
       30,   30,   38,   37,   30,   37,   37,   34,   37,   37,
       37,   37,   37,   30,   36,   34,   33,   33,   35,   32,
        3,   36,   21,   36,   18,   36,   12,   36,   15,   36,
       11,   36,   13,   36,   22,   36,    1,    1,   24,   36,
       14,   36,    2,   36,   27,   36,   17,   36,    1,   23,
       36,    4,   36,    1,    1,    6,   36,    1,    1,    1,
       31,    9,   36,   20,   36,   29,    8,   36,   26,   36,
        1,    1,    1,   28,   16,   36,    5,    7,   10,   19,
       36,   25
    } ;

static yyconst short int yy_accept[370] =
    {   0,
        1,    2,    3,    4,    5,    7,    8,   10,   11,   12,
       13,   14,   15,   15,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,   18,   18,   18,   18,   19,   19,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   23,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   27,   29,
       29,   29,   29,   31,   31,   31,   31,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   35,   35,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   38,   39,   39,   41,   41,   43,
       43,   43,   43,   45,   45,   45,   45,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   52,   52,   52,   54,   55,
       55,   56,   56,   56,   56,   56,   56,   56,   56,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   59,   60,   61,   62,   62,   64,   66,

       66,   67,   67,   67,   69,   69,   69,   69,   69,   69,
       71,   71,   71,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   74,   74,   74,   75,   75,   75,   75,
       75,   75,   75,   77,   77,   78,   78,   78,   78,   78,
       78,   78,   78,   79,   79,   79,   79,   79,   79,   80,
       82,   82,   82,   82,   82,   82,   82,   83,   83
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,   10,   11,
       12,   13,   13,   13,   13,   13,   14,   15,    1,    1,
        1,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   35,   41,   42,   35,
       16,    1,   17,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   35,   41,
       42,   35,    1,   43,    1,    1,    1,    1,   44,    1,
        1,    1,    1,    1,    1,    1,   44,    1,    1,    1,
       44,    1,    1,    1,    1,    1,   44,    1,    1,    1,
        1,    1,    1,   44,    1,   44,    1,    1,    1,    1,
       44,    1,    1,    1,    1,    1,    1,    1,   44,    1,
        1,    1,   44,    1,    1,    1,    1,    1,   45,    1,
        1,    1,    1,    1,    1,   44,    1,   44,    1,    1,
        1,    1,    1,    1,   46,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    2,    3,    4,    1,    5,    6,    7,    7,
        7,    7,    7,    7,    8,    1,    1,    1,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    1,    3,    3,    3
    } ;

static yyconst short int yy_base[382] =
    {   0,
        0,    0,  861,  862,   45,   46,  853,  844,   74,   79,
       80,   50,  853,  862,   91,   92,   93,   94,   97,  101,
      102,   95,   99,  104,  107,  103,  105,  114,  123,  106,
      110,  129,  134,  850,  848,  840,  125,  134,  120,  160,
      148,  149,  152,   57,  153,  156,  158,  161,  155,  162,
      163,  170,  171,  173,  177,  178,  183,  189,   59,  190,
      191,  192,  197,  194,  200,  203,  204,  219,  846,  197,
      196,  198,  232,  210,  217,  230,  211,  233,  220,  243,
      244,  245,  247,  249,  248,  253,  254,  251,  252,  255,
      256,  258,  259,  261,  271,  260,  264,  274,  270,  268,

      278,  289,  290,  280,  862,    0,  282,  838,  837,  293,
      298,  299,  301,  302,  304,  303,  305,  309,  308,  310,
      846,  845,  313,  314,  321,  315,  325,  327,  316,  322,
      844,  843,  324,  323,  328,  842,  335,  343,  344,  841,
      345,  346,  349,  348,  350,  382,  347,  424,  840,  355,
      839,  353,  425,  426,  427,  428,  357,  862,  862,  360,
      429,  430,  358,  431,  359,  434,  432,  862,  862,  433,
      435,  438,  862,  440,  441,  449,  862,  445,  439,  437,
      442,    0,  475,  512,  442,  838,  862,  436,  862,  837,
      522,  523,  524,  836,  525,  526,  527,  835,  512,  817,

      529,  530,  532,  533,  535,  539,  536,  538,  540,  542,
      545,  546,  549,  440,  551,  832,  862,  557,  862,  552,
      558,  562,  862,  563,  564,  565,  862,  804,  809,  803,
      807,  566,  567,  572,  575,  862,  810,  368,  578,  581,
      827,  582,  583,  826,    0,  611,  581,  593,  595,  596,
      599,  825,  797,  796,  800,  801,  600,  606,  608,  605,
      794,  622,  607,  610,  862,  601,  612,  862,  647,    0,
      816,  684,  818,  694,  817,  695,  816,  815,  862,  781,
      813,  796,  789,  810,  696,  795,  779,  697,  700,  807,
      701,  702,  803,  802,  801,  862,  703,  862,  862,  772,

      862,  780,  768,  862,  705,  773,  768,  704,  706,  862,
      708,  707,  795,  711,  776,  761,  764,  741,  755,  710,
      709,  712,  769,  713,  733,  763,  736,  744,  724,  716,
      721,  717,  752,  754,  738,  862,  750,  724,  734,  719,
      725,  726,  862,  731,  862,  728,  742,  727,  731,  729,
      718,  613,  862,  732,  630,  640,  638,  609,  862,  862,
      597,  591,  590,  617,  601,  473,  862,  862,  765,  765,
      772,  361,  359,  781,  209,   94,  785,  789,  791,  793,
      795
    } ;

static yyconst short int yy_def[382] =
    {   0,
      368,    1,  368,  368,  368,  368,  369,  370,  370,  370,
      370,  368,  371,  368,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  368,  369,  368,  370,  370,  370,  370,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  368,  368,  370,
      370,  370,   40,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  368,  372,  370,  370,  370,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  368,  368,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  368,  368,  371,
      371,  371,  371,  371,  371,  371,  371,  368,  368,  371,
      371,  371,  368,  371,  371,  371,  368,  371,  371,  371,
      371,  373,  368,  368,  368,  371,  368,  371,  368,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  368,  368,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  374,  183,  368,  368,  371,  368,  371,
      371,  371,  368,  371,  371,  371,  368,  368,  368,  368,
      368,  371,  371,  371,  371,  368,  368,  371,  371,  371,
      371,  371,  371,  371,  375,  373,  368,  371,  371,  371,
      371,  371,  368,  368,  368,  368,  371,  371,  371,  371,
      368,  371,  371,  371,  368,  371,  371,  368,  368,  376,
      377,  368,  378,  368,  368,  371,  371,  371,  368,  368,
      368,  368,  368,  371,  371,  368,  368,  371,  371,  371,
      371,  371,  375,  376,  379,  368,  371,  368,  368,  368,

      368,  368,  368,  368,  371,  368,  368,  371,  371,  368,
      371,  371,  380,  371,  368,  368,  368,  368,  368,  371,
      371,  371,  381,  371,  368,  368,  368,  368,  368,  371,
      371,  371,  368,  371,  368,  368,  368,  368,  368,  371,
      371,  371,  368,  368,  368,  368,  368,  371,  371,  371,
      368,  368,  368,  371,  368,  368,  371,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,    0,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368
    } ;

static yyconst short int yy_nxt[909] =
    {   0,
        4,    5,    5,    5,    6,    4,    4,    4,    7,    7,
        7,    7,    7,    7,    4,    4,    4,    4,    8,    8,
        8,    8,    8,    9,    8,    8,    8,    8,    8,    8,
        8,   10,    8,    8,    8,    8,    8,   11,    8,    8,
        8,    8,    4,    4,    4,    4,   12,   12,   12,   13,
       14,   12,   12,   12,   13,   15,   16,   13,   13,   13,
       79,   14,   96,   14,   17,   13,   18,   19,   20,   21,
       13,   13,   22,   23,   13,   24,   25,   26,   27,   28,
       13,   13,   29,   30,   31,   32,   13,   13,   35,   13,
       13,   13,   37,   35,   35,   14,   14,   14,   14,   14,

       40,   14,  294,   14,   40,   14,   14,   14,   14,   14,
       14,   14,   42,   41,   14,   39,   44,   38,   14,   45,
       43,   55,   48,   46,   51,   57,   54,   14,   52,   47,
       56,   49,   60,   14,   35,   58,   59,   50,   65,   35,
       53,   63,   68,   68,   68,   68,   68,   68,   35,   61,
       66,   67,   14,   14,   70,   62,   14,   14,   72,   14,
       14,   64,   14,   71,   14,   14,   14,   14,   73,   73,
       73,   73,   73,   73,   14,   14,   90,   14,   75,   84,
       76,   14,   14,   87,   77,   74,   80,   14,   85,   83,
       78,   82,   81,   14,   14,   14,   14,   91,   14,   86,

       92,   14,   89,  102,   14,   88,  103,   14,   14,   93,
       35,   35,   35,  101,   14,   14,   97,  269,   94,   95,
      109,   14,   99,   98,   14,  108,  100,  105,  105,  105,
      105,  105,  105,  107,   14,  114,  111,   14,  116,  104,
      110,  110,  110,  110,  110,  110,  112,   14,   14,   14,
      113,   14,   14,   14,  115,   14,   14,   14,   14,   14,
       14,  117,   14,   14,   14,   14,  118,  120,   14,  121,
      122,  125,   14,  128,   14,   14,  119,  123,   14,  126,
      131,  127,   14,  124,   14,  135,  141,  132,  129,  133,
      134,  130,  140,   14,   14,  137,   35,   14,  147,  142,

      136,  138,   14,   14,  109,   14,   14,   14,   14,   14,
      143,  144,   14,   14,   14,  139,  145,   14,   14,   14,
       14,  149,  152,  150,  153,   14,   14,   14,   14,   14,
      157,   14,   14,  163,  151,  160,  161,  148,  155,   14,
      154,  156,  162,  164,  167,  165,  170,   14,   14,   14,
       14,  166,   14,   14,   14,  184,  185,   14,  171,   14,
      172,   14,   14,   14,   14,  175,  176,  214,  179,  146,
      180,  262,   14,  174,  190,  199,  181,  195,  196,  201,
      178,  121,  182,  182,  188,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  182,  182,  182,  182,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,  245,  200,   14,
      216,  216,  216,   14,  246,  191,  186,  205,  218,  193,
      207,  208,  198,  192,  194,  197,  202,  206,  203,  209,
      204,  210,  211,  212,  213,  182,  182,  367,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  182,  182,  182,
      182,  216,  216,  216,  216,  216,   14,   14,   14,   14,
       14,   14,  228,   14,   14,  229,   14,   14,  230,  236,
       14,  221,   14,   14,   14,  226,   14,  225,  220,   14,
       14,  224,  237,   14,  233,  232,   14,  222,  245,  235,
      121,   14,   14,  242,  234,  246,   14,   14,   14,   14,
       14,   14,  243,  238,  241,  239,   14,  240,  121,   14,
      244,  263,   14,  194,  249,   14,   14,   14,  248,  272,
      273,  273,  274,  275,  275,  250,  251,   14,  257,   14,

       14,  252,  258,   14,   14,   14,  260,  267,  259,   14,
       14,   14,   14,  264,   14,  276,   14,  266,  270,  271,
      271,  271,  271,  271,  271,  286,   14,  277,  285,  194,
      194,  284,  366,  365,  364,  278,  363,  289,  291,  362,
      288,  361,  360,  292,  359,  358,  290,  182,  182,  356,
      182,  182,  182,  182,  245,  182,  182,  182,  182,  182,
      182,  246,  182,  182,  182,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  182,
      182,  182,  182,  275,  275,  275,  275,  275,  296,   14,

       14,   14,  275,  275,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,  309,  311,
       14,   14,  320,   14,  312,   14,  297,  331,  308,   14,
       14,   14,  305,   14,  332,   14,   14,  321,  322,  330,
      314,  121,  194,  324,  355,  341,  353,  349,  342,  334,
      352,  351,  347,  346,  345,  348,  344,  340,  343,  270,
      339,  354,  338,  350,  194,  337,  194,  336,  357,   34,
      335,   34,   36,   36,   13,   13,  270,  329,   13,  328,
       13,  182,  327,  182,  182,  182,  182,  182,  182,  182,
      295,  295,  275,  326,  325,  275,  313,  313,  323,  323,

      333,  333,  270,  319,  318,  317,  316,  315,  270,  270,
      270,  310,  307,  306,  304,  303,  302,  301,  300,  299,
      298,  296,  296,  270,  287,  283,  282,  281,  280,  279,
      268,  265,  261,  256,  255,  254,  253,  247,  231,  227,
      223,  219,  217,  189,  187,  177,  173,  169,  168,  159,
      158,   35,   35,  106,   35,   69,   33,   14,   35,   33,
      368,    3,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368
    } ;

static yyconst short int yy_chk[909] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    6,
        6,   12,   12,   12,    6,    6,    6,    6,    6,    6,
       44,   44,   59,   59,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    9,    6,
        6,    6,    9,   10,   11,   15,   16,   17,   18,   22,

       16,   19,  376,   23,   15,   20,   21,   26,   24,   27,
       30,   25,   18,   17,   31,   11,   19,   10,   28,   19,
       18,   23,   20,   19,   21,   25,   22,   29,   21,   19,
       24,   20,   28,   32,   39,   26,   27,   20,   30,   37,
       21,   29,   33,   33,   33,   33,   33,   33,   38,   28,
       31,   32,   41,   42,   37,   28,   43,   45,   39,   49,
       46,   29,   47,   38,   40,   48,   50,   51,   40,   40,
       40,   40,   40,   40,   52,   53,   54,   54,   42,   48,
       42,   55,   56,   51,   42,   41,   45,   57,   49,   47,
       43,   46,   45,   58,   60,   61,   62,   54,   64,   50,

       55,   63,   53,   65,   65,   52,   66,   66,   67,   56,
       71,   70,   72,   64,   74,   77,   60,  375,   57,   58,
       72,   75,   62,   61,   79,   71,   63,   68,   68,   68,
       68,   68,   68,   70,   76,   77,   74,   78,   79,   67,
       73,   73,   73,   73,   73,   73,   75,   80,   81,   82,
       76,   83,   85,   84,   78,   88,   89,   86,   87,   90,
       91,   80,   92,   93,   96,   94,   81,   82,   97,   83,
       84,   86,  100,   89,   99,   95,   81,   85,   98,   87,
       92,   88,  101,   85,  104,   96,  100,   93,   90,   94,
       95,   91,   99,  102,  103,   98,  107,  110,  110,  101,

       97,   98,  111,  112,  107,  113,  114,  116,  115,  117,
      102,  103,  119,  118,  120,   98,  104,  123,  124,  126,
      129,  112,  115,  113,  116,  125,  130,  134,  133,  127,
      120,  128,  135,  126,  114,  123,  124,  111,  118,  137,
      117,  119,  125,  127,  130,  128,  133,  138,  139,  141,
      142,  129,  144,  143,  145,  147,  147,  152,  134,  150,
      135,  157,  163,  165,  160,  138,  139,  373,  142,  372,
      144,  238,  238,  137,  152,  163,  145,  157,  160,  165,
      141,  143,  146,  146,  150,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,

      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  148,  153,
      154,  155,  156,  161,  162,  164,  167,  170,  166,  171,
      188,  180,  172,  179,  174,  175,  181,  214,  164,  178,
      185,  185,  185,  176,  214,  153,  148,  171,  188,  155,
      174,  175,  162,  154,  156,  161,  166,  172,  167,  176,
      170,  178,  179,  180,  181,  183,  183,  366,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  184,  184,  184,  184,  184,  191,  192,  193,  195,
      196,  197,  199,  201,  202,  199,  203,  204,  199,  205,
      207,  192,  208,  206,  209,  197,  210,  196,  191,  211,
      212,  195,  205,  213,  202,  201,  220,  193,  215,  204,
      206,  218,  221,  211,  203,  215,  222,  224,  225,  226,
      232,  233,  212,  207,  210,  208,  234,  209,  218,  235,
      213,  239,  239,  220,  222,  240,  242,  243,  221,  247,
      247,  247,  247,  247,  247,  224,  225,  248,  232,  249,

      250,  226,  233,  251,  257,  266,  235,  243,  234,  260,
      258,  263,  259,  240,  264,  248,  267,  242,  246,  246,
      246,  246,  246,  246,  246,  259,  262,  250,  258,  260,
      249,  257,  365,  364,  363,  251,  362,  263,  266,  361,
      262,  358,  357,  267,  356,  355,  264,  269,  269,  352,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  272,  272,  272,  272,  272,  274,  276,

      285,  288,  274,  274,  289,  291,  292,  297,  308,  305,
      309,  312,  311,  321,  320,  314,  322,  324,  289,  291,
      330,  332,  308,  340,  292,  331,  276,  321,  288,  341,
      342,  348,  285,  350,  322,  349,  354,  309,  311,  320,
      297,  305,  312,  314,  351,  331,  347,  341,  332,  324,
      346,  344,  339,  338,  337,  340,  335,  330,  334,  333,
      329,  350,  328,  342,  348,  327,  349,  326,  354,  369,
      325,  369,  370,  370,  371,  371,  323,  319,  371,  318,
      371,  374,  317,  374,  374,  374,  374,  374,  374,  374,
      377,  377,  378,  316,  315,  378,  379,  379,  380,  380,

      381,  381,  313,  307,  306,  303,  302,  300,  295,  294,
      293,  290,  287,  286,  284,  283,  282,  281,  280,  278,
      277,  275,  273,  271,  261,  256,  255,  254,  253,  252,
      244,  241,  237,  231,  230,  229,  228,  216,  200,  198,
      194,  190,  186,  151,  149,  140,  136,  132,  131,  122,
      121,  109,  108,   69,   36,   35,   34,   13,    8,    7,
        3,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
#include <stdio.h>
#include <conio.h>
#define YYDEBUG 0
#line 714 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "lexer.l"



#line 869 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 862 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 31 "lexer.l"
{ fprintf(yyout, "%s", "URL"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 32 "lexer.l"
{ fprintf(yyout, "%s", "CARGO"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "lexer.l"
{ fprintf(yyout, "%s", "ESTADO"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "lexer.l"
{ fprintf(yyout, "%s", "K_VERSION"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "lexer.l"
{ fprintf(yyout, "%s", "K_FIRMA_DIGITAL"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "lexer.l"
{ fprintf(yyout, "%s", "K_EMPRESAS"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "lexer.l"
{ fprintf(yyout, "%s", "K_NOMBRE_EMPRESA"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "lexer.l"
{ fprintf(yyout, "%s", "K_FUNDACION"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "lexer.l"
{ fprintf(yyout, "%s", "K_DIRECCION"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "lexer.l"
{ fprintf(yyout, "%s", "K_INGRESOS_ANUALES"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "lexer.l"
{ fprintf(yyout, "%s", "K_PYME"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "lexer.l"
{ fprintf(yyout, "%s", "K_LINK"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "lexer.l"
{ fprintf(yyout, "%s", "K_CALLE"); } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "lexer.l"
{ fprintf(yyout, "%s", "K_CIUDAD"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "lexer.l"
{ fprintf(yyout, "%s", "K_PAIS"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "lexer.l"
{ fprintf(yyout, "%s", "K_DEPARTAMENTOS"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "lexer.l"
{ fprintf(yyout, "%s", "K_NOMBRE"); } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "lexer.l"
{ fprintf(yyout, "%s", "K_JEFE"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "lexer.l"
{ fprintf(yyout, "%s", "K_SUBDEPARTAMENTOS"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "lexer.l"
{ fprintf(yyout, "%s", "K_EMPLEADOS"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "lexer.l"
{ fprintf(yyout, "%s", "K_EDAD"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 52 "lexer.l"
{ fprintf(yyout, "%s", "K_CARGO"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 53 "lexer.l"
{ fprintf(yyout, "%s", "K_SALARIO"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 54 "lexer.l"
{ fprintf(yyout, "%s", "K_ACTIVO"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 55 "lexer.l"
{ fprintf(yyout, "%s", "K_FECHA_CONTRATACION"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 56 "lexer.l"
{ fprintf(yyout, "%s", "K_PROYECTOS"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "lexer.l"
{ fprintf(yyout, "%s", "K_ESTADO"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 58 "lexer.l"
{ fprintf(yyout, "%s", "K_FECHA_INICIO"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 59 "lexer.l"
{ fprintf(yyout, "%s", "K_FECHA_FIN"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 60 "lexer.l"
{ ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 61 "lexer.l"
{ fprintf(yyout, "%s", "DATE"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 62 "lexer.l"
{ fprintf(yyout, "%s", "BOOL"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 63 "lexer.l"
{ fprintf(yyout, "%s", "FLOAT"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 64 "lexer.l"
{ fprintf(yyout, "%s", "INTEGER"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 65 "lexer.l"
{ fprintf(yyout, "%s", "NULL_VALUE"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 66 "lexer.l"
{ fprintf(yyout, "%s", "STRING"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "lexer.l"
ECHO;
	YY_BREAK
#line 1145 "lexer.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 368);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 68 "lexer.l"


